### ISSUE TITLE
Valor de resistencia RP* en pin reset del Atmega328

### ISSUE THREAD

**Issue by spark2k06** [ManuFerHi/ZX-GO-#2]
Cuál es el valor de la resistencia RP* en la conexión Reset del Atmega328 para su programación por el conector USB?

![image](https://user-images.githubusercontent.com/3509674/90117466-4489db80-dd57-11ea-9d79-43ec156b0085.png)

**Comment by ManuFerHi** [comment]
Cero, es un puente de estaño, el proceso es el siguiente:
1- Grabar bootloader por ICSP.
2- Hacer puente de estaño en RP.
3- Grabar firmware por USB.

El motivo es que a mi programador ICSP no le sienta los 5V en la señal DTR, pero supongo que depende del programador no será necesario programar antes de hacer el puente.

**Comment by spark2k06** [comment]
Entendido, gracias!
